services:
  server:
    build: .
    container_name: server
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgis/postgis:15-3.3
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
  
  client:
    image: nginx:latest
    container_name: client
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    networks:
      - app-network
    depends_on:
      - server
    
volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge