version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "5000:5000"
    # Carica le variabili dal file .env
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgis/postgis:15-3.3
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge