services:
  backend:
    build: .
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgis/postgis:15-3.3
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - backend
    
volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge