services:
  backend:
    build: .
    container_name: server
    ports:
      - "5000:5000" # Mappa la porta 5000
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    depends_on:
      - db
    networks:
      - app-network

  db:
    # ... (il servizio db rimane invariato)
    image: postgis/postgis:15-3.3
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge